services:
  db:
    image: postgres:15-alpine
    container_name: teamevents_db_test
    environment:
      POSTGRES_USER: teamevents
      POSTGRES_PASSWORD: teamevents123
      POSTGRES_DB: teamevents
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_test:/var/lib/postgresql/data

volumes:
  postgres_data_test:

